FROM jupyter/base-notebook

USER root

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER jovyan

RUN pip install --no-cache-dir \
    pyspark==4.1.1 \
    pandas==2.2.2 \
    numpy \
    scipy \
    qpsolvers \
    quadprog \
    matplotlib \
    seaborn \
    plotly \
    networkx \
    community 