services:

  postgres:
    image: postgres:15
    container_name: fintek-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: finance123
      POSTGRES_DB: fintek_db
      POSTGRES_MAX_CONNECTIONS: 100
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance -d fintek_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fintek_network


  spark-master:
    build:
      context: .
      dockerfile: dockerfilegpu.spark
    container_name: spark-master
    restart: unless-stopped
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_EXTRA_CLASSPATH=/opt/bitnami/spark/jars/rapids-4-spark.jar
      - SPARK_CONF_spark.plugins=com.nvidia.spark.SQLPlugin
      - SPARK_CONF_spark.rapids.sql.enabled=true
    ports:
      - "8081:8080"
      - "7077:7077"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - fintek_network


  spark-worker:
    build:
      context: .
      dockerfile: dockerfilegpu.spark
    container_name: spark-worker
    restart: unless-stopped
    depends_on:
      spark-master:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXTRA_CLASSPATH=/opt/bitnami/spark/jars/rapids-4-spark.jar
      - SPARK_CONF_spark.plugins=com.nvidia.spark.SQLPlugin
      - SPARK_CONF_spark.rapids.sql.enabled=true
      - SPARK_CONF_spark.rapids.memory.gpu.allocSize=1024m
      - SPARK_CONF_spark.rapids.memory.gpu.maxAllocSize=4096m
    ports:
      - "8082:8081"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - fintek_network


  jupyter:
    build:
      context: .
      dockerfile: dockerfilegpu.jupyter
    container_name: fintek-jupyter
    restart: unless-stopped
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=fintek123
    depends_on:
      - spark-master
      - postgres
    networks:
      - fintek_network


networks:
  fintek_network:
    driver: bridge