FROM public.ecr.aws/bitnami/spark:4.1.1

USER root

RUN apt-get update && apt-get install -y wget

RUN wget -q https://jdbc.postgresql.org/download/postgresql-42.7.3.jar -O /opt/bitnami/spark/jars/postgresql-42.7.3.jar

RUN chown 1001:1001 /opt/bitnami/spark/jars/postgresql-42.7.3.jar

USER 1001